### PR TITLE
added Chiara blog

### PR DESCRIPTION
**Pull request by reshamas**
@cmarmo @laurburke 

Would you like to review before merging?

Also, I don't know if there is a way to see the preview of the blog post, maybe with GitHub actions?
It's something I've seen with projects hosted on Netlify, I think.

### CODE REVIEW

**Review by laurburke — COMMENTED** [review]
The featured image is still the one from Juan Martín's interview. Other than that, looks good!

**Comment by reshamas** [comment]
@thomasjpfan I can't seem to assign @cmarmo as a Reviewer to this PR.

**Comment by reshamas** [comment]
> The featured image is still the one from Juan Martín's interview. Other than that, looks good!

@laurburke updated feature image.

**Comment by thomasjpfan** [comment]
I gave the triage team "triage" permissions to this repo. They should now appear on the "reviewers" list.

**Pull request merged**
