### PR TITLE
Update Salta sprint post

### PR DESCRIPTION
**Pull request by jmloyola**
Update the post with more information, photos and acknowledgment.

### CODE REVIEW

**Comment by reshamas** [comment]
@jmloyola 
Can we add this too:
https://twitter.com/ScipyLA/status/1573710649963724802

**Comment by jmloyola** [comment]
@reshamas Done. Let me know what do you think

**Comment by reshamas** [comment]
@jmloyola Can we find out who took the photos and add photo credit?

example code:
```
<figure>
 <img src="/assets/images/posts_images/sprint-neurips-2011.jpeg" alt="men at a happy hour" max-width="20%" max-height="20%" /> 
 <figcaption>
 NeurIPS Granada, Spain scikit-learn sprint, March 2011; Photo credit: <a href="http://gael-varoquaux.info">Gael Varoquaux</a>; (from left to right): Vlad Niculae, Mathieu Blondel, Bertrand Thirion, James Bergtra, Jake VanderPlas, Andreas Mueller, Alexandre Gramfort
 </figcaption>
</figure>
```

@jmloyola 
Any list of PRs submitted that we can add?

@symeneses 
Is there anything you would like to add to this blog?

**Comment by jmloyola** [comment]
There were no PRs during the sprint. Some folks are working towards their first PR, but I don't know when they'll be able to continue working on that.

Concerning the photo credits, I'm asking the organizers for that.

**Review by reshamas — APPROVED** [review]

**Comment by reshamas** [comment]
Thanks @jmloyola

**Pull request merged**
