### PR TITLE
Cross post Maren's interview

### PR DESCRIPTION
**Pull request by symeneses**
Cross posting interview. It solves #91.

### CODE REVIEW

**Comment by symeneses** [comment]
Let me know what you think @reshamas. We could add Maren's website in the author section.

**Comment by reshamas** [comment]
@symeneses Thanks for this pull request.  Some suggestions:  
a)  for "featured image", let's use this one:  https://blog.dataumbrella.org/images/blogs/maren_interview.png

b) for authors, we can list both me and Maren.  Here is an example from a past interview:  
REF:  https://raw.githubusercontent.com/scikit-learn/blog/main/_posts/2022-01-08-jml-interview.md

```text
postauthors:
  - name: Reshama Shaikh
    website: https://reshamas.github.io
    image: reshama_shaikh.jpeg 
  - name: Juan Martín Loyola
    website: https://jmloyola.github.io/
    image: juan-martin-loyola.jpeg
---
```

c)  For @marenwestermann image, we can use the one on LinkedIn:
[marenwestermann](https://www.linkedin.com/in/dr-maren-westermann-0b8575144/)

d) For Maren's URL, we can use LinkedIn as well, unless Maren prefers Twitter or her website.

**Comment by symeneses** [comment]
@reshamas Suggestions applied. I used the LinkedIn's profile, @marenwestermann let me know if I should change it.

**Comment by reshamas** [comment]
@symeneses Looks great!! Thank you.

**Comment by marenwestermann** [comment]
This looks great! Thanks a lot @reshamas and @symeneses ! :)

**Pull request merged**
