### PR TITLE
Update 2023-07-31-paris-dev-sprint.md

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
Towards #165

Mostly order names alphabetically

Also change the sum from 33 to 33

### CODE REVIEW

**Comment by reshamas** [comment]
@GaelVaroquaux 
First of all, congratulations on your first PR to the blog repo!  Thank you for the PR. We hope you enjoyed the Welcome banner!

a small comment: 
The blog has a date of 2023-07-31.  Can we change it to 2023-09-12 ? or 2023-09-10 ?

**Comment by GaelVaroquaux** [comment]
> We hope you enjoyed the Welcome banner!

I looooooooved it!! Do we have something as nice for scikit-learn?

> The blog has a date of 2023-07-31. Can we change it to 2023-09-12 ? or 2023-09-10 ?

Sure! Shall I do this in this PR?

**Comment by GaelVaroquaux** [comment]
> Sure! Shall I do this in this PR?

Date change done

**Comment by reshamas** [comment]
> > Sure! Shall I do this in this PR?
> 
> Date change done

I thought the actual file name needed to be changed.  But, maybe not?

**Comment by reshamas** [comment]
I'll merge it in and see what the date shows.

**Comment by GaelVaroquaux** [comment]
> I thought the actual file name needed to be changed. But, maybe not?

Ha, I was being not clever. Thanks for handling it.

**Pull request merged**
